### PR TITLE
Map keys of custom types should serialize using MarshalText when available

### PR DESCRIPTION
**Pull request by styeung**
This is to address the issue filed [here](https://github.com/json-iterator/go/issues/459).

### CODE REVIEW

**Comment by AllenX2018** [comment]
Thanks for the bug report and the patch. 

1. Could you please also check if map keys of custom types are deserialized correctly? I think they may have the similar problem
2. Can you move the test case to value_tests/map_test.go?

**Comment by styeung** [comment]
Thanks for the feedback.  

1. Yes, turns out `unmarshal` had the same problem as well.  Updated the `decoderOfMapKey` method correct this behavior.
2. Tests moved

**Comment by styeung** [comment]
@AllenX2018 ping!

**Comment by AllenX2018** [comment]
Merged, Thanks!

**Pull request merged**
