### PR TITLE
add to support time.Time parse format `2006-01-02T15:04:05`

### PR DESCRIPTION
**Pull request by 1046102779**
测试结果：目前只提供了解析，后续会提供序列化
image

### CODE REVIEW

**Comment by Kisesy** [comment]
我觉得应开放时间格式自定义

**Comment by taowen** [comment]
you can create a new package. And implement the Decoder/Encoder function for various date format. The functionality can be plugin by RegisterTypeEncoder/RegisterTypeDecoder

**Comment by taowen** [comment]
like this one https://github.com/json-iterator/java/blob/master/src/main/java/com/jsoniter/extra/JdkDatetimeSupport.java

**Comment by 1046102779** [comment]
if i creates a new decoder package,  i can't  access jsoniter's any method such as `func (c *Iterator) nextToken() ` and its members.  What should I do?

**Comment by 1046102779** [comment]
image
image

**Comment by taowen** [comment]
like this https://github.com/json-iterator/go/blob/master/jsoniter_customize_test.go#L14

**Pull request closed without merging**
